export const MOOD_CREATE_SUCCESS = 'MOOD_CREATE_SUCCESS';
export const MOOD_CREATE_FAIL = 'MOOD_CREATE_FAIL';
export const MOOD_LIST_SUCCESS = 'MOOD_LIST_SUCCESS';
export const MOOD_LIST_FAIL = 'MOOD_LIST_FAIL';
export const MOOD_DELETE_SUCCESS = 'MOOD_DELETE_SUCCESS';
export const MOOD_DELETE_FAIL = 'MOOD_DELETE_FAIL';

export const GARMENT_CREATE_SUCCESS = 'GARMENT_CREATE_SUCCESS';
export const GARMENT_CREATE_FAIL = 'GARMENT_CREATE_FAIL';
export const GARMENT_LIST_SUCCESS = 'GARMENT_LIST_SUCCESS';
export const GARMENT_LIST_FAIL = 'GARMENT_LIST_FAIL';
export const GARMENT_DELETE_SUCCESS = 'GARMENT_DELETE_SUCCESS';
export const GARMENT_DELETE_FAIL = 'GARMENT_DELETE_FAIL';

export const OUTFIT_CREATE_SUCCESS = 'OUTFIT_CREATE_SUCCESS';
export const OUTFIT_CREATE_FAIL = 'OUTFIT_CREATE_FAIL';
export const OUTFIT_LIST_SUCCESS = 'OUTFIT_LIST_SUCCESS';
export const OUTFIT_LIST_FAIL = 'OUTFIT_LIST_FAIL';
export const OUTFIT_DELETE_SUCCESS = 'OUTFIT_DELETE_SUCCESS';
export const OUTFIT_DELETE_FAIL = 'OUTFIT_DELETE_FAIL';
